language: bash
git:
  depth: false
os:
  - osx
  - windows
  - linux
env:
  global:
    - TERM=dumb
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
  matrix:
    - JDK="adopt@1.11"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt@1.12"
    - JDK="adopt-openj9@1.12"
    - JDK="adopt@1.13"
    - JDK="adopt-openj9@1.13"
install:
  - curl "${GRAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh
  - source .install-jdk-travis.sh
script: ./gradlew runAll
before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - bash .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/